FROM python:3.11-slim

WORKDIR /app
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      libmagic1 libmagic-dev default-jre-headless \
      tesseract-ocr && \
    rm -rf /var/lib/apt/lists/*
COPY backend/ /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]